name: nepc-dev
channels:
        - conda-forge
dependencies:
        - ipython
        - ipython_genutils
        - jpeg
        - jupyter
        - jupyter_client
        - numpy
        - pandas
        - python
        - matplotlib
        - tabulate
        - pytest
        - pytest-cov
        - sphinx
        - numpydoc
        - pip
        - pip:
                - quadpy
                - pylint
                - pdfminer.six
                - pdfplumber
                - mysql-connector-python==8.0.17
                - autopep8
                - livereload
                - formic2
                - sphobjinv
