#!/bin/bash

# PROVIDE THE PATH FOR THE INNER AND OUTER REGION EXECUTABLES
export bininner="../UKRmol-in/bin/"
export binouter="..//UKRmol-out/bin/"

export OMP_NUM_THREADS=8

cp inputs/scattering.integrals.inp ./inp
mkdir -p output
rm moints
mpirun -ilp64 -n 2 -ppn 2 ${bininner}/scatci_integrals
mv log_file.0 output/target.integrals.out

ln -sf moints fort.16
ln -sf moints fort.17
ln -sf moints fort.22

#TARGET
${bininner}/congen < inputs/target.congen.singlet.A.inp > output/target.congen.singlet.A.out || exit
mpirun -ilp64 -n 1 -ppn 1 ${bininner}/mpi-scatci < inputs/target.scatci.singlet.A.inp > output/target.scatci.singlet.A.out || exit

${bininner}/congen < inputs/target.congen.triplet.A.inp > output/target.congen.triplet.A.out || exit
mpirun -ilp64 -n 1 -ppn 1 ${bininner}/mpi-scatci < inputs/target.scatci.triplet.A.inp > output/target.scatci.triplet.A.out || exit

${bininner}/congen < inputs/target.congen.singlet.B.inp > output/target.congen.singlet.B.out || exit
mpirun -ilp64 -n 1 -ppn 1 ${bininner}/mpi-scatci < inputs/target.scatci.singlet.B.inp > output/target.scatci.singlet.B.out || exit

${bininner}/congen < inputs/target.congen.triplet.B.inp > output/target.congen.triplet.B.out || exit
mpirun -ilp64 -n 1 -ppn 1 ${bininner}/mpi-scatci < inputs/target.scatci.triplet.B.inp > output/target.scatci.triplet.B.out || exit

${bininner}/denprop < inputs/target.denprop.inp > output/target.denprop.out || exit

#SCATTERING
${bininner}/congen < inputs/scattering.congen.doublet.A.inp > output/scattering.congen.doublet.A.serial.out || exit
mpirun -ilp64 -n 1 -ppn 1 ${bininner}/mpi-scatci < inputs/scattering.scatci.doublet.A.inp > output/scattering.scatci.doublet.A.serial.out || exit

${binouter}/outer < inputs/scattering.outerres.doublet.A.inp > output/scattering.outerres.doublet.A.out || exit
mv fort.100 xsec_a
mv fort.110 eigenph_a

${bininner}/congen < inputs/scattering.congen.doublet.B.inp > output/scattering.congen.doublet.B.serial.out || exit
mpirun -ilp64 -n 1 -ppn 1 ${bininner}/mpi-scatci < inputs/scattering.scatci.doublet.B.inp > output/scattering.scatci.doublet.B.serial.out || exit

${binouter}/outer < inputs/scattering.outerres.doublet.B.inp > output/scattering.outerres.doublet.B.out || exit
mv fort.100 xsec_b
mv fort.110 eigenph_b
